### ISSUE TITLE
[SDKTECHNO-67] Add PySpark: mono-node

### ISSUE THREAD

**Issue by Jo314** [saagie/technologies#166]
Provide a Jupyter Notebook be able to run a pyspark job in mono-node in Saagie V2 application

Bonus : Access to the SparkUI

**Comment by finalspy** [comment]
Spark mono node is working and displays a sparkUI.
But currently it is limited to only one notebook at a time because sparkUI reverse proxy doen't works properly and keeps issuing HTTP 302 redirects to /jobs/ when trying to access /proxy/local-***/*.* resources.

The problem doen't come from nginx configuration bu directly from the embedded Jetty.
Source code seems to be here : 
https://github.com/apache/spark/blob/branch-2.4/core/src/main/scala/org/apache/spark/ui/JettyUtils.scala

Logs just indicate 'null' then issues a 302 ... no stacktrace nor further informations.

Some of the tried resources ... 
https://stackoverflow.com/questions/45971127/wrong-css-location-of-spark-application-ui/45993324
https://8vi.cat/configure-nginx-as-reverse-proxy-for-sparkui/
https://issues.apache.org/jira/browse/SPARK-30240
